# Example ranger config
# Symlink with: bash scripts/80_dotfiles.sh ranger

set preview_images true
set preview_images_method kitty
set vcs_aware true
set draw_borders true
set show_hidden true
set confirm_on_delete multiple

# Use system editor
set editor vim

# Shortcuts
map <C-n> shell $EDITOR %s
map g? help
