# Example Flameshot configuration
# Symlinked to ~/.config/flameshot/flameshot.ini
#   bash scripts/80_dotfiles.sh flameshot

[General]
startupLaunch=true
showHelp=false
savePath=~/Pictures/Screenshots
savePathFixed=true
copyPathAfterSave=true
showDesktopNotification=false

[Shortcuts]
TYPE_COPY=Ctrl+C
TYPE_SAVE=Ctrl+S
TYPE_OPEN_APP=Return
TYPE_UNDO=Ctrl+Z
TYPE_REDO=Ctrl+Shift+Z
